services:
  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 ecom.wsgi:application
    volumes:
      - .:/app
      - ./media:/app/media  # Mount media từ local vào container
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: 123123123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media  # Mount media từ local vào container
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
    ports:
      - "8080:80"
volumes:
  postgres_data:
