# Generated by Django 4.2 on 2025-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this box to mark the category as active and visible.', verbose_name='Active'),
        ),
    ]
