# Generated by Django 4.2 on 2025-02-25 03:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to false to soft-delete the address.'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark this address as default.'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the address.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the address.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=django_countries.fields.CountryField(help_text='Country of the address.', max_length=2),
        ),
    ]
