# Generated by Django 4.2 on 2025-02-25 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('name', models.CharField(help_text='Name of the promotion', max_length=100)),
                ('code', models.CharField(help_text='Unique promo code (e.g., SUMMER10)', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (fixed amount or percentage)', max_digits=10)),
                ('applies_to', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('cart', 'Entire Cart')], default='cart', max_length=20)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount required', max_digits=10, null=True)),
                ('max_uses', models.IntegerField(default=1, help_text='Maximum number of times this promo can be used')),
                ('used_count', models.IntegerField(default=0, help_text='Number of times this promo has been used')),
                ('start_date', models.DateTimeField(help_text='Promotion start date')),
                ('end_date', models.DateTimeField(help_text='Promotion end date')),
                ('active', models.BooleanField(default=True, help_text='Is the promotion active?')),
                ('category', models.ForeignKey(blank=True, help_text='Applicable category (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Applicable product (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='AppliedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('discount_applied', models.DecimalField(decimal_places=2, help_text='Amount discounted', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order that applied this promotion', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('promotion', models.ForeignKey(help_text='Applied promotion', on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applied Promotion',
                'verbose_name_plural': 'Applied Promotions',
            },
        ),
    ]
