# Generated by Django 4.2 on 2025-02-25 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('name', models.CharField(help_text='Name of the shipping method (e.g., Standard, Express)', max_length=100)),
                ('carrier', models.CharField(help_text='Shipping carrier (e.g., FedEx, DHL)', max_length=100)),
                ('estimated_days', models.IntegerField(help_text='Estimated delivery time in days')),
                ('base_cost', models.DecimalField(decimal_places=2, help_text='Fixed shipping fee', max_digits=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, help_text='Additional cost per kilogram', max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Is this shipping method active?')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('full_name', models.CharField(help_text='Full name of the recipient', max_length=255)),
                ('address_line1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, unit, etc.', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('province', models.CharField(blank=True, help_text='State or province', max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(help_text='Country', max_length=2)),
                ('postal_code', models.CharField(help_text='ZIP or postal code', max_length=20)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking number for shipment', max_length=50, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, help_text='Date when the order was shipped', null=True)),
                ('delivered_date', models.DateTimeField(blank=True, help_text='Date when the order was delivered', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the shipment', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('shipping_method', models.ForeignKey(help_text='Chosen shipping method', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingmethod')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
    ]
