# Generated by Django 4.2 on 2025-02-25 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('date', models.DateField(help_text='The date for which the sales report is generated', unique=True)),
                ('total_orders', models.IntegerField(default=0, help_text='Total number of orders placed on this date')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated on this date', max_digits=15)),
                ('total_customers', models.IntegerField(default=0, help_text='Total number of unique customers on this date')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of the product view')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product that was viewed', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed the product (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('cart_items', models.JSONField(help_text='Stores cart items as JSON, including product IDs, quantities, etc.')),
                ('abandoned_at', models.DateTimeField(auto_now_add=True, help_text='Time the cart was abandoned')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who abandoned the cart', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart Abandonment',
                'verbose_name_plural': 'Cart Abandonments',
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='BestSellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('total_sold', models.IntegerField(default=0, help_text='Total number of units sold')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The best-selling product', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Best Selling Product',
                'verbose_name_plural': 'Best Selling Products',
                'ordering': ['-total_sold'],
            },
        ),
    ]
